package dev.turtywurty.turtyapi.games;

import lombok.Data;

@Data
public class Game {
    private int[] age_ratings;
    private double aggregated_rating = -1;
    private int aggregated_rating_count = -1;
    private int[] alternative_names;
    private int[] artworks;
    private int[] bundles;
    private int category = -1;
    private String checksum;
    private int collection = -1;
    private int[] collections;
    private int cover = -1;
    private long created_at = -1;
    private int[] dlcs;
    private int[] expanded_games;
    private int[] expansions;
    private int[] external_games;
    private long first_release_date = -1;
    private int follows = -1;
    private int[] forks;
    private int franchise = -1;
    private int[] franchises;
    private int[] game_engines;
    private int[] game_localizations;
    private int[] game_modes;
    private int[] genres;
    private int hypes = -1;
    private int[] involved_companies;
    private int[] keywords;
    private int[] languageSupports;
    private int[] multiplayer_modes;
    private String name;
    private int parent_game = -1;
    private int[] platforms;
    private int[] player_perspectives;
    private int[] ports;
    private double rating = -1;
    private int rating_count = -1;
    private int[] release_dates;
    private int[] remakes;
    private int[] remasters;
    private int[] screenshots;
    private int[] similar_games;
    private String slug;
    private int standalone_expansions = -1;
    private int status = -1;
    private String storyline;
    private String summary;
    private int[] tags;
    private int[] themes;
    private double total_rating = -1;
    private int total_rating_count = -1;
    private long updated_at = -1;
    private String url;
    private int version_parent = -1;
    private String version_title;
    private int[] videos;
    private int[] websites;
}
