name: Publish Dockerfile to GitHub Packages (Self-hosted)

on:
  workflow_dispatch:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: darealturtywurty/turtyapi

jobs:
  publish:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle shadowJar
        run: ./gradlew shadowJar

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          mkdir temp
          cp $GITHUB_WORKSPACE/build/libs/TurtyAPI-all.jar temp/TurtyAPI.jar
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .
          rm -rf temp

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
